<?php
/**
 * Styles and scripts for the module 
 *
 * @package    HNG2
 * @subpackage youtube_for_editor
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 *             
 * @var module $this_module
 */

use hng2_base\module;
?>

<!-- youtube link embedder for editor -->

<script type="text/javascript"
        src="<?= $config->full_root_path ?>/<?= $this_module->name ?>/media/global_functions~v<?=$config->scripts_version?>.js"></script>

