<?php
/**
 * Messages and other details for the button and the dialog
 *
 * @package    BardCanvas
 * @subpackage giphy_for_bardcanvas
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<!-- Giphy for Bardcanvas tinymce strings -->

<div id="giphy_for_bardcanvas_tinymce_strings" style="display: none;">
    <div class="title"><?= $this_module->language->tinymce_strings->title ?></div>
</div>
